### ISSUE TITLE
have you used the wrong math function? 

### ISSUE THREAD

**Issue by dreamingtech** [Sssmeb/BloomFilter#1]
I calculated m and k on this website
https://hur.st/bloomfilter/
The result is not equal with your code, maybe you have used the wrong function.

Yours: 

m = - (n * (math.log10(p)) / (math.log10(2))**2)
k = m / n * math.log10(2)
Right
m = - (n * math.log(p)) / (math.log(2)**2)
k = m / n * math.log(2)

**Comment by Sssmeb** [comment]
Yep! Thank you so much for pointing out my careless mistake! Has been revised

**Comment by dreamingtech** [comment]
参考你的代码, 我又重写了一下
https://github.com/dreamingtech/bloom_filter

**Comment by Sssmeb** [comment]
hh一开始还以为是国际友人。 看了您的代码，单例和分布式锁都是很好的想法！我也打算优化一下我的代码。 但是好像没有看到您在add和exists操作用到锁。还有分布式判断是时候，您好像是把所有键都遍历判断了一遍，这样的话效果和没扩容是一样的...

最后，给您提两个建议：1. 个人觉得不需要每行都写注释，看起来好繁杂...可以在重点操作注释，其他注释可统一写在函数定义下。
2. 个人觉得，对于用户来说，实例化布隆过滤器需要关注的点是用户需要存放的数据和期望是误判率。其他例如种子数量或者内存大小等参数最好对用户透明。
