### ISSUE TITLE
哥们，代码测试没问题，但是融合到scrapy-redis里面永远判断错误

### ISSUE THREAD

**Issue by lvouran** [Sssmeb/BloomFilter#2]
拿出来单测代码没任何问题，但是重写了request_seen只有第一个判断为不存在，剩下的全部判断存在
`代码如下：
`class BFilterMiddleware(RFPDupeFilter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.bf = RedisFilter(self.server, redis_key=self.key)
        self.bf.start(100000000, 0.0001)

    # 重写一下加密方式
    def request_seen(self, request):
        # 考虑一下是否只需要对 pageid 加密就行
        docid_byte = bytes('docId', encoding='utf8')
        if docid_byte in request.body:
            fp = request.meta.get('body').get('docId')
            print(fp)
            if self.bf.is_exists(fp):
                print('此请求已经存在不需要重复请求...', fp)
                return True
            else:
                self.bf.add(fp)
                return False
``

**Comment by Sssmeb** [comment]
emm如果单测没问题的话，那就是配置出问题了。可以检查一下scrapy-redis的去重器配置、或者相关的redis函数是否有问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lvouran"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月1日(星期天) 晚上9:02
收件人:&nbsp;"Sssmeb/BloomFilter"<BloomFilter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Sssmeb/BloomFilter] 哥们，代码测试没问题，但是融合到scrapy-redis里面永远判断错误 (#2)




拿出来单测代码没任何问题，但是重写了request_seen只有第一个判断为不存在，剩下的全部判断存在
 代码如下： class BFilterMiddleware(RFPDupeFilter):
 def init(self, *args, **kwargs):
 super().init(*args, **kwargs)
 self.bf = RedisFilter(self.server, redis_key=self.key)
 self.bf.start(100000000, 0.0001)
 # 重写一下加密方式 def request_seen(self, request):     # 考虑一下是否只需要对 pageid 加密就行     docid_byte = bytes('docId', encoding='utf8')     if docid_byte in request.body:         fp = request.meta.get('body').get('docId')         print(fp)         if self.bf.is_exists(fp):             print('此请求已经存在不需要重复请求...', fp)             return True         else:             self.bf.add(fp)             return False  
``

**Comment by lvouran** [comment]
可能能力有限，断点的话，一个是锁的时间会直接返回false，导致之后报错，一个是在释放锁的时候，被你会捕获异常然后直接pass，之后导致内部对迭代器next的时候报错。。。我照你的改了个简单的不带锁的先用着，，自己在慢慢研究研究，，谢谢
